### ISSUE TITLE
Plot styling

### ISSUE THREAD

**Issue by mzechmeister** [3fon3fonov/trifon#12]
Periodograms
*  x-axis:
   "days" -> "period [d]"
  "frequency" -> "frequency [1/d]"
  no  exponentinal format
Phase plot
* day -> phase [days]

**Comment by 3fon3fonov** [comment]
Thanks, I fully agree, but I was neglecting these. Will be fixed in the next git push.
Meanwhile, keep in mind that when you want to export a plot for your paper you can quite easily do a further customization by exporting to the matplotlib window. 

Right click on your favorite plot --> export --> Matplotlib Window --> Play! 

There are still some limitations in this exporter, which I need to fix (like you cannot change the color of the data error-bars and the font size of the labels), but otherwise works very good and you can produce easily a custom publication quality plots.

**Comment by 3fon3fonov** [comment]
Done. Anything else?
