### ISSUE TITLE
MCMC: AttributeError: 'signal_fit' object has no attribute 'ld_m'

### ISSUE THREAD

**Issue by mzechmeister** [3fon3fonov/trifon#19]
`run MCMC` and the stderr output:
```
Traceback (most recent call last):
  File "gui.py", line 4050, in worker_mcmc
    self.set_tra_ld()        
  File "gui.py", line 448, in set_tra_ld
    fit.ld_m[i] = "quadratic"        
AttributeError: 'signal_fit' object has no attribute 'ld_m'
```

**Comment by 3fon3fonov** [comment]
Did that happen from your imported session? set_tra_ld was introduced a long time ago so I am wondering if you are using old RVmod __init__.py or your session is old. Can you try the same on a fresh git clone? Also, this may be related to the fact that you are usually ignoring the "right" batman package, while I strongly suggest to install it.

**Comment by 3fon3fonov** [comment]
Or perhaps you had commented this line in the RVmod:

self.init_transit_params()

In order to not get an error on Batman? 

Let me know.

**Comment by mzechmeister** [comment]
I implemented the lines in https://github.com/3fon3fonov/trifon/issues/17#issue-465355837.
Maybe almost as commenting that line.

**Comment by 3fon3fonov** [comment]
Then this will not work because you need to initialize 

        self.ld_models = ["uniform", "linear", "quadratic", "nonlinear"]
        self.ld_m = ["quadratic", "quadratic",  "quadratic", "quadratic", "quadratic", "quadratic", "quadratic", "quadratic", "quadratic", "quadratic"]    #limb darkening model
        self.ld_u = {k: [0.1, 0.3 ] for k in range(10)}    
        self.tr_params.limb_dark = "quadratic"      #limb darkening model
        self.tr_params.u =  [0.1, 0.3 ]            
 
Before you run mcmc, nested sampling or SciPy optimizers they will check for these values, which are updated by the GUI if needed. You may try to move these out of the  self.init_transit_params()
but i think it is way easier to simply install batman. In the bash scripts, I also provide local batman install,
you may want to try this (but still you need to remove the old one).
        
      
        self.tr_params_use = [False, False,False,False,False,False,False]

**Comment by mzechmeister** [comment]
I don't do any transit stuff sofar. So it should not dependent on that.

**Comment by 3fon3fonov** [comment]
Fair, I can try to gray-out the options if some of them are not installed (batman,emcee, etc.) so you can continue using the RV code without crashes. I will need some time to do that and also for tests. Meanwhile, do we agree that the problem you had is triggered by your intervention and there is no general issue?

**Comment by 3fon3fonov** [comment]
OK Mathias,

I just included a similar (but more sophisticated) fix. Now if you don't have batman or you have the wrong one, you should still be able to boot the ES and use the RV part including the mcmc and Nest. Samp, Orbital Evol, etc. Tell me if it works because I don't have the "wrong" batman.

**Comment by mzechmeister** [comment]
Still the same error when running MCMC.

**Comment by 3fon3fonov** [comment]
Can you please make a brand new git clone? I have a bad feeling that some files are not updated. after your git puls. also please remove the old "wrong batman" If I cannot reproduce the error I cannot help. The tool should work without any problem without batman.

**Comment by mzechmeister** [comment]
Still the same MCMC after a brand new git clone.

To get it run, I 
(1) commented out `self.set_tra_ld()` in gui.py
(2) changed `tr_params = None #obj.tr_params` in RVmod/__init__.py

How do I get the corner plots?

**Comment by 3fon3fonov** [comment]
Mathias, I cannot reproduce your problems with the current code. All is fine on my side. However, I bet everything resides to the fact that you are very stubborn and you don't want to remove the wrong batman package.... and I cannot reproduce your errors because I refuse to install something that has nothing to do with the ES just to test the error.  Also: 

```
try:
    import batman as batman   
    try: 
        bat_test = batman.TransitParams()
        batman_not_found = False 
        bat_test = 0     
    except (ImportError, KeyError, AttributeError) as e:     
        batman_not_found = True 
except (ImportError, KeyError) as e:
    batman_not_found = True
    pass     

```

was also added to the RVmod's init.py which should resolve your problem forever :)

For the corner plots, please explore "Models param. --> MCMC param."
